'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("signINver2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActionIconNewPNG24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActionIconNewPNG24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property addNewJob1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("addNewJob1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property addNewJob2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("addNewJob2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addNewJob2_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addNewJob2_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addNewJob21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addNewJob21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addNewJobPNG_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addNewJobPNG_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property admin24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("admin24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provider=Microsoft.Jet.OLEDB.4.0; Data Source=\\attermserv01\company data\Action\Action Traffic.mdb.
        '''</summary>
        Friend ReadOnly Property atmConnStr01() As String
            Get
                Return ResourceManager.GetString("atmConnStr01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ATMmainPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ATMmainPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property atmMenuBarBG_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atmMenuBarBG_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property atmMenuBarBG_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atmMenuBarBG_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property atmToolStripBG_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atmToolStripBG_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property atmToolStripBG_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atmToolStripBG_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bgForm1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bgForm1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bgForm2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bgForm2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bgForm3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bgForm3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bike_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bike_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property clock_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clock_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provider=Microsoft.Jet.OLEDB.4.0; Data Source=\\attermserv01\company data\MHS Pre Production\signIN\db1.mdb.
        '''</summary>
        Friend ReadOnly Property connStr01() As String
            Get
                Return ResourceManager.GetString("connStr01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provider=Microsoft.Jet.OLEDB.4.0; Data Source=\\attermserv01\company data\Michigan Highway\MHS Database.mdb.
        '''</summary>
        Friend ReadOnly Property connStrMHS01() As String
            Get
                Return ResourceManager.GetString("connStrMHS01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Customers_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Customers_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Database2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Database2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Database2_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Database2_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Database2_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Database2_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Database2_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Database2_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Database21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Database21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Database3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Database3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Database3_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Database3_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dataTable16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dataTable16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DeleteRecordPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeleteRecordPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DesktopPNG_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DesktopPNG_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property editConsole1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("editConsole1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property editConsole1_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editConsole1_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property editConsole1_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editConsole1_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property editConsole1_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editConsole1_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property global2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("global2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property globalTakeOff3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("globalTakeOff3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property globalTakeOff4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("globalTakeOff4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property globalTakeOff5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("globalTakeOff5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HomePNG_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HomePNG_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to c:\sIv2\signImages\.
        '''</summary>
        Friend ReadOnly Property imgPath() As String
            Get
                Return ResourceManager.GetString("imgPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property info1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("info1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ingo_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ingo_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provider=Microsoft.Jet.OLEDB.4.0; Data Source=\\attermserv01\company data\MHS Pre Production\signIN\materialsInventory.mdb.
        '''</summary>
        Friend ReadOnly Property inventoryConnStr01() As String
            Get
                Return ResourceManager.GetString("inventoryConnStr01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jimsHouse24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jimsHouse24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Jobs() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Jobs", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jobs_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jobs_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to c:\sIv2\Jobs\.
        '''</summary>
        Friend ReadOnly Property jobsDirectory() As String
            Get
                Return ResourceManager.GetString("jobsDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property key_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property key_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kingMoFo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kingMoFo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property legend1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("legend1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property legend11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("legend11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property legend2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("legend2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lightningBolt16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lightningBolt16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lion24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lion24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menuStripBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menuStripBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mhsLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mhsLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property michaelPeakeCrane() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("michaelPeakeCrane", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mmm_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mmm_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MMMLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MMMLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MontrealCanadiesn_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MontrealCanadiesn_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property new_extruded_1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("new_extruded_1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_extruded_1_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_extruded_1_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_extruded_1_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_extruded_1_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_extruded_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_extruded_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property new_flatsheet_1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("new_flatsheet_1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_flatsheet_1_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_flatsheet_1_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_flatsheet_1_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_flatsheet_1_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_flatsheet_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_flatsheet_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property new_plywood_1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("new_plywood_1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_plywood_1_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_plywood_1_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_plywood_1_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_plywood_1_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_plywood_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_plywood_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nextPayItem16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nextPayItem16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property none1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("none1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property PDF() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PDF", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PDF_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PDF_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PDF_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PDF_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PDF_641() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PDF_641", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pushPin24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pushPin24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redWings24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redWings24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reset_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reset_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property SalvageItemsICON() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SalvageItemsICON", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SalvageItemsPNG_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SalvageItemsPNG_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property save_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property saveAll_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveAll_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property search_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property search_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provider=Microsoft.Jet.OLEDB.4.0;Jet OLEDB:Database Password=j0hns0n; Data Source=\\attermserv01\company data\MHS Pre Production\signIN\secured.mdb;Persist Security Info=False.
        '''</summary>
        Friend ReadOnly Property securedConnStr() As String
            Get
                Return ResourceManager.GetString("securedConnStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SecurityPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SecurityPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \\attermserv01\company data\MHS Pre Production\signImages\.
        '''</summary>
        Friend ReadOnly Property serverImgPath() As String
            Get
                Return ResourceManager.GetString("serverImgPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property shipper() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("shipper", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property shipper2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("shipper2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shipper21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shipper21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property showHide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("showHide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sI_Splash_EXP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sI_Splash_EXP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property signCode1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("signCode1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property signCode1_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("signCode1_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property signCode2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("signCode2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property signCode2_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("signCode2_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property signINMain_1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("signINMain_1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property signINMain_2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("signINMain_2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property signInMain_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("signInMain_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property signinmain_4() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("signinmain_4", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property signINMain_41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("signINMain_41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property signInMain_5() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("signInMain_5", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property signINMain_51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("signINMain_51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property signINMain_6() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("signINMain_6", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property signInSplashScreen_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("signInSplashScreen_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sIv22_Splash_EXP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sIv22_Splash_EXP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sIv2SplashScreen_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sIv2SplashScreen_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SpartanHelmet_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpartanHelmet_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Spartans_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spartans_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TigersD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TigersD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property toolStripBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolStripBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
